'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { apiErrorMessage } from '../../lib/api/error';
import { authenticatedActionRequest, clearSession } from '../../lib/auth/session';
import type { ActionState, BoardRole, SystemRole } from '../../lib/api/types';
import { allowedAttachmentTypes, boardSchema, columnSchema, MAX_ATTACHMENT_BYTES, memberSchema, profileSchema, taskSchema, uuidSchema } from './validation';

const errorState = (error: unknown): ActionState => ({ status: 'error', message: apiErrorMessage(error) });
const json = (method: string, body?: unknown): RequestInit => ({ method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
const values = (data: FormData) => Object.fromEntries(data.entries());

export async function updateProfileAction(_: ActionState, data: FormData): Promise<ActionState> { const p = profileSchema.safeParse(values(data)); if (!p.success) return { status:'error', message:'Check the form.', fieldErrors:p.error.flatten().fieldErrors }; try { await authenticatedActionRequest('/users/me', json('PATCH', p.data)); revalidatePath('/profile'); return {status:'success',message:'Profile updated.'}; } catch(e){return errorState(e);} }
export async function createBoardAction(_: ActionState, data: FormData): Promise<ActionState> { const p=boardSchema.safeParse(values(data)); if(!p.success)return {status:'error',message:'Enter a valid board name.'}; let id:string;try{id=(await authenticatedActionRequest<{id:string}>('/boards',json('POST',p.data))).id;}catch(e){return errorState(e);}revalidatePath('/dashboard');redirect(`/boards/${id}`); }
export async function updateBoardAction(_: ActionState,data:FormData):Promise<ActionState>{const id=String(data.get('boardId'));const p=boardSchema.safeParse(values(data));if(!uuidSchema.safeParse(id).success||!p.success)return {status:'error',message:'Invalid board details.'};try{await authenticatedActionRequest(`/boards/${id}`,json('PATCH',p.data));revalidatePath(`/boards/${id}`);return {status:'success',message:'Board updated.'};}catch(e){return errorState(e);}}
export async function deleteBoardAction(data:FormData){const id=String(data.get('boardId'));if(uuidSchema.safeParse(id).success)await authenticatedActionRequest(`/boards/${id}`,{method:'DELETE'});revalidatePath('/dashboard');redirect('/dashboard');}
export async function createColumnAction(_:ActionState,data:FormData):Promise<ActionState>{const id=String(data.get('boardId'));const p=columnSchema.safeParse(values(data));if(!p.success)return {status:'error',message:'Enter a column name.'};try{await authenticatedActionRequest(`/boards/${id}/columns`,json('POST',p.data));revalidatePath(`/boards/${id}`);return {status:'success'};}catch(e){return errorState(e);}}
export async function renameColumnAction(data:FormData){const id=String(data.get('columnId'));await authenticatedActionRequest(`/columns/${id}`,json('PATCH',{name:String(data.get('name'))}));revalidatePath(String(data.get('path')));}
export async function deleteColumnAction(data:FormData){await authenticatedActionRequest(`/columns/${data.get('columnId')}`,{method:'DELETE'});revalidatePath(String(data.get('path')));}
export async function reorderColumnsAction(boardId:string,columnIds:string[]){await authenticatedActionRequest('/columns/reorder',json('PATCH',{boardId,columnIds}));revalidatePath(`/boards/${boardId}`);}
export async function createTaskAction(_:ActionState,data:FormData):Promise<ActionState>{const columnId=String(data.get('columnId'));const p=taskSchema.safeParse(values(data));if(!p.success)return {status:'error',message:'Enter valid task details.'};try{await authenticatedActionRequest(`/columns/${columnId}/tasks`,json('POST',{...p.data,assigneeId:p.data.assigneeId||null}));revalidatePath(String(data.get('path')));return {status:'success'};}catch(e){return errorState(e);}}
export async function updateTaskAction(_:ActionState,data:FormData):Promise<ActionState>{const id=String(data.get('taskId'));const p=taskSchema.safeParse(values(data));if(!p.success)return {status:'error',message:'Enter valid task details.'};try{await authenticatedActionRequest(`/tasks/${id}`,json('PATCH',{...p.data,assigneeId:p.data.assigneeId||null}));revalidatePath(String(data.get('path')));return {status:'success',message:'Task updated.'};}catch(e){return errorState(e);}}
export async function deleteTaskAction(data:FormData){await authenticatedActionRequest(`/tasks/${data.get('taskId')}`,{method:'DELETE'});revalidatePath(String(data.get('path')));}
export async function moveTaskAction(taskId:string,columnId:string,position:number,path:string){await authenticatedActionRequest(`/tasks/${taskId}/move`,json('PATCH',{columnId,position}));revalidatePath(path);}
export async function reorderTasksAction(columnId:string,taskIds:string[],path:string){await authenticatedActionRequest('/tasks/reorder',json('PATCH',{columnId,taskIds}));revalidatePath(path);}
export async function addMemberAction(_:ActionState,data:FormData):Promise<ActionState>{const boardId=String(data.get('boardId'));const p=memberSchema.safeParse(values(data));if(!p.success)return {status:'error',message:'Enter a registered email and role.'};try{await authenticatedActionRequest(`/boards/${boardId}/members`,json('POST',p.data));revalidatePath(`/boards/${boardId}`);return {status:'success'};}catch(e){return errorState(e);}}
export async function updateMemberAction(data:FormData){const boardId=String(data.get('boardId'));await authenticatedActionRequest(`/boards/${boardId}/members/${data.get('userId')}`,json('PATCH',{role:data.get('role') as BoardRole}));revalidatePath(`/boards/${boardId}`);}
export async function removeMemberAction(data:FormData){const boardId=String(data.get('boardId'));await authenticatedActionRequest(`/boards/${boardId}/members/${data.get('userId')}`,{method:'DELETE'});revalidatePath(`/boards/${boardId}`);}
export async function transferOwnerAction(data:FormData){const boardId=String(data.get('boardId'));await authenticatedActionRequest(`/boards/${boardId}/owner`,json('PATCH',{userId:data.get('userId')}));revalidatePath(`/boards/${boardId}`);}
export async function uploadAttachmentAction(_:ActionState,data:FormData):Promise<ActionState>{const file=data.get('file');if(!(file instanceof File)||file.size===0)return {status:'error',message:'Choose a file.'};if(file.size>MAX_ATTACHMENT_BYTES)return {status:'error',message:'File must be 10 MB or smaller.'};if(!allowedAttachmentTypes.has(file.type))return {status:'error',message:'Unsupported file type.'};const body=new FormData();body.set('file',file);try{await authenticatedActionRequest(`/tasks/${data.get('taskId')}/attachments`,{method:'POST',body});revalidatePath(String(data.get('path')));return {status:'success'};}catch(e){return errorState(e);}}
export async function deleteAttachmentAction(data:FormData){await authenticatedActionRequest(`/attachments/${data.get('attachmentId')}`,{method:'DELETE'});revalidatePath(String(data.get('path')));}
export async function updateSystemRoleAction(data:FormData){await authenticatedActionRequest(`/admin/users/${data.get('userId')}/role`,json('PATCH',{role:data.get('role') as SystemRole}));revalidatePath('/admin/users');}
export async function logoutAllAction(){await authenticatedActionRequest('/auth/logout-all',{method:'POST'});await clearSession();redirect('/login');}
