import { redirect } from 'next/navigation';
import { Badge } from '../../../../components/ui/badge';
import { Button } from '../../../../components/ui/button';
import { Card } from '../../../../components/ui/card';
import { Input } from '../../../../components/ui/input';
import { updateSystemRoleAction } from '../../../../features/kanban/actions';
import { getAdminUsers } from '../../../../lib/api/kanban';
import { getCurrentUser } from '../../../../lib/auth/session';
export default async function AdminUsersPage({searchParams}:{searchParams:Promise<{page?:string;search?:string}>}){const me=await getCurrentUser();if(me.systemRole!=='ADMIN')redirect('/dashboard');const q=await searchParams;const page=Math.max(1,Number(q.page)||1);const search=q.search?.trim()||'';const data=await getAdminUsers(page,search);return <div className="space-y-6"><div><h1 className="text-3xl font-semibold">System users</h1><p className="mt-2 text-muted">Global roles do not grant board access.</p></div><form className="flex max-w-xl gap-2"><Input name="search" defaultValue={search} placeholder="Search name or email"/><Button>Search</Button></form><Card className="overflow-x-auto"><table className="w-full min-w-2xl text-left text-sm"><thead className="border-b border-line text-muted"><tr><th className="p-4">User</th><th>Role</th><th>Change role</th></tr></thead><tbody>{data.items.map(u=><tr className="border-b border-line/60" key={u.id}><td className="p-4"><p className="font-medium">{u.name}</p><p className="text-muted">{u.email}</p></td><td><Badge>{u.systemRole}</Badge></td><td><form action={updateSystemRoleAction} className="flex gap-2"><input type="hidden" name="userId" value={u.id}/><select name="role" defaultValue={u.systemRole} disabled={u.id===me.id} className="rounded-lg border border-line bg-canvas px-3"><option>USER</option><option>ADMIN</option></select><Button variant="secondary" disabled={u.id===me.id}>Save</Button></form></td></tr>)}</tbody></table></Card><p className="text-sm text-muted">Page {data.page} of {Math.max(1,data.totalPages)} · {data.total} users</p></div>}
